### ISSUE TITLE
Publish gem to RubyGems

### ISSUE THREAD

**Issue by kinnell** [kinnell/groupme-ruby-gem#5]
## Tasks
- [x] Finalize gem name
- [x] Research best way to do it with RubyGems
- [x] Publish to RubyGems

**Comment by kinnell** [comment]
Published! https://rubygems.org/gems/groupme-api
